
-- Schema para o Sistema de Monitoramento Industrial
-- Execute estes comandos no seu projeto Supabase

-- 1. Criar tabela de máquinas
CREATE TABLE IF NOT EXISTS maquinas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL,
    localizacao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Criar tabela de leituras de sensores
CREATE TABLE IF NOT EXISTS leituras_sensores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_maquina UUID NOT NULL REFERENCES maquinas(id) ON DELETE CASCADE,
    temperatura FLOAT4 NOT NULL,
    umidade FLOAT4 NOT NULL,
    vibracao_x INT4 NOT NULL,
    vibracao_y INT4 NOT NULL,
    vibracao_z INT4 NOT NULL,
    timestamp_leitura TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_leituras_sensores_id_maquina ON leituras_sensores(id_maquina);
CREATE INDEX IF NOT EXISTS idx_leituras_sensores_timestamp ON leituras_sensores(timestamp_leitura DESC);
CREATE INDEX IF NOT EXISTS idx_leituras_sensores_maquina_timestamp ON leituras_sensores(id_maquina, timestamp_leitura DESC);

-- 4. Habilitar RLS (Row Level Security) - opcional, mas recomendado
ALTER TABLE maquinas ENABLE ROW LEVEL SECURITY;
ALTER TABLE leituras_sensores ENABLE ROW LEVEL SECURITY;

-- 5. Criar políticas básicas (permitir acesso para usuários autenticados)
CREATE POLICY "Permitir leitura de máquinas" ON maquinas FOR SELECT USING (true);
CREATE POLICY "Permitir leitura de leituras" ON leituras_sensores FOR SELECT USING (true);

-- 6. Para desenvolvimento/testes, você pode criar políticas mais permissivas:
-- CREATE POLICY "Permitir tudo em máquinas" ON maquinas FOR ALL USING (true);
-- CREATE POLICY "Permitir tudo em leituras" ON leituras_sensores FOR ALL USING (true);

-- 7. Comentários para documentação
COMMENT ON TABLE maquinas IS 'Tabela que armazena informações das máquinas monitoradas';
COMMENT ON TABLE leituras_sensores IS 'Tabela que armazena as leituras dos sensores de cada máquina';
COMMENT ON COLUMN leituras_sensores.vibracao_x IS 'Valor do ADC para vibração no eixo X (0-4095)';
COMMENT ON COLUMN leituras_sensores.vibracao_y IS 'Valor do ADC para vibração no eixo Y (0-4095)';
COMMENT ON COLUMN leituras_sensores.vibracao_z IS 'Valor do ADC para vibração no eixo Z (0-4095)';
